-- Database: carrito
-- DROP DATABASE IF EXISTS carrito;

CREATE TABLE CLIENT (
	ID_CLIENT SERIAL PRIMARY KEY,
	CLIENT_NAME VARCHAR(30) NOT NULL,
	CLIENT_LAST_NAME VARCHAR(30) NOT NULL,
	CLIENT_EMAIL VARCHAR(100) UNIQUE NOT NULL,
	CLIENT_ADDRESS VARCHAR(100) NOT NULL,
	CLIENT_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT (
	ID_PRODUCT SERIAL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR(200) NOT NULL,
	PRODUCT_UNIT_PRICE NUMERIC(12, 2) NOT NULL,
	PRODUCT_IMAGE VARCHAR(200) NOT NULL
);

CREATE TABLE WISH (
	ID_WISH SERIAL PRIMARY KEY,
	FK_CLIENT INT NOT NULL,
	WISH_DATE DATE NOT NULL,
	WISH_STATE VARCHAR(10) NOT NULL,
	WISH_TOTAL NUMERIC(12, 2) NOT NULL,
	CONSTRAINT FK_CLIENT_WISH FOREIGN KEY (FK_CLIENT) REFERENCES CLIENT (ID_CLIENT)
);

CREATE TABLE WISH_DETAIL (
	ID_WISH_DETAIL SERIAL PRIMARY KEY,
	FK_WISH INT NOT NULL,
	FK_PRODUCT INT NOT NULL,
	WISH_DETAIL_AMOUNT INT NOT NULL,
	WISH_DETAIL_SUBTOTAL NUMERIC(12, 2) NOT NULL,
	CONSTRAINT FK_WISHDETAIL_WISH FOREIGN KEY (FK_WISH) REFERENCES WISH (ID_WISH),
	CONSTRAINT FK_WISHDETAIL_PRODUCT FOREIGN KEY (FK_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
);

CREATE TABLE WISH_HISTORY (
	ID_WISH_HISTORY SERIAL PRIMARY KEY,
	FK_WISH INT NOT NULL,
	WISH_HISTORY_DATE DATE NOT NULL,
	WISH_HISTORY_STATE VARCHAR(10) NOT NULL,
	WISH_HISTORY_FINAL_PRICE NUMERIC(12, 2) NOT NULL,
	CONSTRAINT FK_WISHHISTORY_WISH FOREIGN KEY (FK_WISH) REFERENCES WISH (ID_WISH)
);

CREATE TABLE INTERNAL_USER (
	ID_INTERNAL_USER SERIAL PRIMARY KEY,
	INTERNAL_USER_NAME VARCHAR(30) NOT NULL,
	INTERNAL_USER_PASSWORD VARCHAR(100) NOT NULL,
	INTERNAL_USER_ROLE VARCHAR(30) NOT NULL
);

CREATE TABLE MAIL (
	ID_MAIL SERIAL PRIMARY KEY,
	MAIL_TYPE VARCHAR(20) NOT NULL,
	MAIL_RECEIVER VARCHAR(100) NOT NULL,
	MAIL_CONTENT VARCHAR(300) NOT NULL
);

INSERT INTO
	CLIENT (
		CLIENT_NAME,
		CLIENT_LAST_NAME,
		CLIENT_EMAIL,
		CLIENT_ADDRESS,
		CLIENT_PASSWORD
	)
VALUES
	(
		'Juan',
		'Perez',
		'juanperez@gmail.com',
		'Larrea 4646',
		'123456789'
	),
	(
		'Marta',
		'Juana',
		'marta@gmail.com',
		'Larrea 4645',
		'12345678'
	),
	(
		'Martina',
		'Morena',
		'morena@gmail.com',
		'Larrea 4644',
		'1234567'
	),
	(
		'Lionel',
		'Perez',
		'lio@gmail.com',
		'Larrea 4643',
		'123456'
	);

INSERT INTO
	PRODUCT (
		PRODUCT_NAME,
		PRODUCT_DESCRIPTION,
		PRODUCT_UNIT_PRICE,
		PRODUCT_IMAGE	
	)
VALUES
	(
		'Paquete a Rio de Janeiro',
		'Viaje fantástico para 2',
		450000,
		'rio_janeiro.jpg'
	),
	(
		'Paquete a Espana',
		'Viaje fantástico para adultos',
		550000,
		'espana.webp'
	),
	(
		'Paquete a Puerto Rico',
		'Hermosas vistas',
		700000,
		'puerto_rico.webp'
	),
	(
		'Paquete a Perú',
		'Bueno, bonito y barato',
		250000,
		'peru.jpg'
	);

INSERT INTO
	WISH (FK_CLIENT, WISH_DATE, WISH_STATE, WISH_TOTAL)
VALUES
	(1, '2025-04-02', 'Pago', 250000),
	(2, '2025-05-07', 'Cancelado', 700000),
	(3, '2025-01-15', 'Pendiente', 450000);

INSERT INTO
	WISH_DETAIL (
		FK_WISH,
		FK_PRODUCT,
		WISH_DETAIL_AMOUNT,
		WISH_DETAIL_SUBTOTAL
	)
VALUES
	(1, 1, 1, 450000),
	(2, 2, 2, 1100000),
	(3, 3, 1, 700000);

INSERT INTO
	WISH_HISTORY (
		FK_WISH,
		WISH_HISTORY_DATE,
		WISH_HISTORY_STATE,
		WISH_HISTORY_FINAL_PRICE
	)
VALUES
	(1, '2024-12-06', 'Pago', 900000),
	(2, '2024-09-06', 'Pago', 700000),
	(3, '2024-04-09', 'Cancelado', 500000);

INSERT INTO
	INTERNAL_USER (
		INTERNAL_USER_NAME,
		INTERNAL_USER_PASSWORD,
		INTERNAL_USER_ROLE
	)
VALUES
	('Martin', 'code12345', 'Agente de viajes'),
	('Paula', 'code1234', 'Asesora de ventas'),
	('Celina', 'code123', 'Coordinadora de ventas'),
	('Ian', 'code12', 'Ejecutivo de ventas');

INSERT INTO
	MAIL (MAIL_TYPE, MAIL_RECEIVER, MAIL_CONTENT)
VALUES
	(
		'CONFIRMACION',
		'marta@gmail.com',
		'Hola Marta, tu paquete turístico a Perú ha sido reservado exitosamente.'
	),
	(
		'CANCELACION',
		'juanperez@gmail.com',
		'Hola Juan, tu paquete turístico a Rio de Janeiro ha sido cancelado exitosamente.'
	),
	(
		'CONFIRMACION',
		'morena@gmail.com',
		'Hola Morena, se ha registrado un inicio de sesión en una Mac 8.'
	);

SELECT
	P.PRODUCT_NAME,
	P.PRODUCT_UNIT_PRICE,
	WD.WISH_DETAIL_AMOUNT,
	WD.WISH_DETAIL_SUBTOTAL
FROM
	WISH_DETAIL WD
	JOIN PRODUCT P ON WD.FK_PRODUCT = P.ID_PRODUCT
	JOIN WISH W ON WD.FK_WISH = W.ID_WISH
WHERE
	W.FK_CLIENT = 3
	AND W.WISH_STATE = 'Pendiente';

INSERT INTO
	WISH_DETAIL (
		FK_WISH,
		FK_PRODUCT,
		WISH_DETAIL_AMOUNT,
		WISH_DETAIL_SUBTOTAL
	)
VALUES
	(
		3,
		4,
		1,
		1 * (
			SELECT
				PRODUCT_UNIT_PRICE
			FROM
				PRODUCT
			WHERE
				ID_PRODUCT = 4
		)
	);

UPDATE WISH_DETAIL
SET
	WISH_DETAIL_AMOUNT = 2,
	WISH_DETAIL_SUBTOTAL = 2 * (
		SELECT
			PRODUCT_UNIT_PRICE
		FROM
			PRODUCT
		WHERE
			ID_PRODUCT = 4
	)
WHERE
	FK_WISH = 3
	AND FK_PRODUCT = 4;

DELETE FROM WISH_DETAIL
WHERE
	FK_WISH = 3
	AND FK_PRODUCT = 4;

SELECT
	*
FROM
	CLIENT
WHERE
	CLIENT_EMAIL = 'juanperez@gmail.com'
	AND CLIENT_PASSWORD = '123456789';

SELECT
	*
FROM
	INTERNAL_USER
WHERE
	INTERNAL_USER_NAME = 'Martin'
	AND INTERNAL_USER_PASSWORD = 'code12345';

SELECT
	*
FROM
	PRODUCT
ORDER BY
	PRODUCT_UNIT_PRICE DESC;

SELECT
	WH.WISH_HISTORY_DATE,
	WH.WISH_HISTORY_STATE,
	WH.WISH_HISTORY_FINAL_PRICE
FROM
	WISH_HISTORY WH
	JOIN WISH W ON WH.FK_WISH = W.ID_WISH
WHERE
	W.FK_CLIENT = 1;

SELECT
	MAIL_TYPE,
	MAIL_CONTENT
FROM
	MAIL
WHERE
	MAIL_RECEIVER = 'marta@gmail.com';

SELECT
	C.CLIENT_NAME,
	C.CLIENT_LAST_NAME,
	W.WISH_DATE,
	WH.WISH_HISTORY_FINAL_PRICE
FROM
	WISH_HISTORY WH
	JOIN WISH W ON WH.FK_WISH = W.ID_WISH
	JOIN CLIENT C ON W.FK_CLIENT = C.ID_CLIENT
WHERE
	LOWER(WH.WISH_HISTORY_STATE) = 'pago';

SELECT
	MAIL_TYPE,
	COUNT(*) AS TOTAL_ENVIADOS
FROM
	MAIL
GROUP BY
	MAIL_TYPE;

SELECT
	C.CLIENT_NAME,
	C.CLIENT_LAST_NAME,
	P.PRODUCT_NAME,
	WD.WISH_DETAIL_AMOUNT,
	WD.WISH_DETAIL_SUBTOTAL
FROM
	CLIENT C
	JOIN WISH W ON C.ID_CLIENT = W.FK_CLIENT
	JOIN WISH_DETAIL WD ON W.ID_WISH = WD.FK_WISH
	JOIN PRODUCT P ON WD.FK_PRODUCT = P.ID_PRODUCT;